[tool.poetry]
name = "cc_hdnnp"
version = "0.1.0"
description = ""
authors = ["Patrick Austin <patrick.austin@stfc.ac.uk>"]

[tool.poetry.dependencies]
python = "^3.6"
ase = "^3.22.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
